// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  images_hero: dynamic(() => import("./ImagesHero")),
  loading: dynamic(() => import("./Loading")),
};
