// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_block: dynamic(() => import("./ContactBlock")),
  exhibition_block: dynamic(() => import("./ExhibitionBlock")),
  favourites: dynamic(() => import("./Favourites")),
  images_hero: dynamic(() => import("./ImagesHero")),
  loading: dynamic(() => import("./Loading")),
  navigation_item: dynamic(() => import("./NavigationItem")),
};
